### ISSUE TITLE
Utilisation des cookies dans laravel

### ISSUE THREAD

**Issue by alexstraubhaar** [HE-Arc/demo-laravel-application#8]
Quel serait le meilleur moyen d'utiliser les cookies dans laravel pour éviter aux utilisateurs du site d'avoir à créer un compte.

**Comment by greut** [comment]
@AlexStraubhaar Décrivez un peu votre usage. Que se passerait-il si un utilisateur n'est pas reconnu lors de sa prochaine visite?

Il y a tout un tas de méthodes pour "identifier" un utilisateur, https://github.com/samyk/evercookie

**Comment by alexstraubhaar** [comment]
@greut Dans le cas de notre projet, on perderait les données des préférences/votes de l'utilisateur et le système de recommendation n'aurait alors plus vraiment d'intérêt.
Puisque ces fonctions de création, récupération de cookies seront régulièrement rappelées, faut-il les mettre dans un helper ou y a-t-il une meilleure façon de faire ?

**Comment by greut** [comment]
Le plus simple me semble être de créer un utilisateur temporaire (avec des [données fictives](https://github.com/fzaninotto/Faker)). Il vous faudra évidemment un moyen de faire la différence entre un vrai compte et un compte _jetable_ , et de concrétiser son compte _jetable_.

Vous pouvez sans autre ignorer le problème de nettoyage. Quand on est une startup, ça fait classe d'avoir plein de comptes (même bidons).

**Comment by greut** [comment]
Si votre formulaire possède un champ `remember` alors, il sera sauvé. Sinon, logguez créez un utilisateur bidon et logguez-le avec `Auth::login($user, true);` Le deuxième argument va y mettre un cookie avec une durée correcte.
